### ISSUE TITLE
Criação de Objetos

### ISSUE THREAD

**Issue by guilherme-gjv** [guilherme-gjv/avaliacao1-2bim-poo#2]
2. Faça as criações dos objetos (pelo menos 2 de cada classe identificada)

**Comment by guilherme-gjv** [comment]
Se fica da escolha do usuário quantos objetos serão criados, isso é meio inútil né?

**Comment by duardoqueiroz** [comment]
https://github.com/guilherme-gjv/avaliacao1-2bim-poo/issues/2#issuecomment-907561127

Na vdd não, pois nós temos mais objetos além dos livros e advogados. Tem também os departamentos, que já foram instanciados, e também os empréstimos.
